name: CI/CD
on:
  push:
    branches:
    - main
  pull_request:
    branches:
      - main

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

env:
  AWS_LAMBDA_NAME: AwsLambdaDotnetWebApi
  AWS_REGION : ap-southeast-2

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Cloning the repo
      uses: actions/checkout@v4

    - name: Setup .NET - uses global.json
      uses: actions/setup-dotnet@v4

    - name: Setup dotnet-coverage for code coverage
      run: dotnet tool install --global dotnet-coverage

    - name: Setup Java for SonarScanner
      uses: actions/setup-java@v4
      with:
        distribution: microsoft
        java-version: 21

    - name: Setup SonarCloud
      run: dotnet tool install --global dotnet-sonarscanner

    - name: Start SonarCloud scan
      run: dotnet sonarscanner begin /k:"${{ vars.SONAR_PROJ_KEY }}" /o:"${{ vars.SONAR_ORG }}" /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url=https://sonarcloud.io /d:sonar.cs.vscoveragexml.reportsPaths=coverage.xml

    - name: Build with dotnet
      run: dotnet build --no-incremental

    - name: Run all tests
      run: dotnet test --configuration Release

    - name: Collect code coverage
      run: dotnet-coverage collect "dotnet test" -f xml -o "coverage.xml"

    - name: End SonarCloud scan
      run: dotnet sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
    - name: Cloning the repo
      uses: actions/checkout@v4

    - name: Setup .NET - uses global.json
      uses: actions/setup-dotnet@v4

    - name: Setup AWS CLI
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::398018169858:role/GitHubActionsRole
        role-session-name: GitHubActionsRole
        aws-region: ${{ env.AWS_REGION }}

    - name: Setup .NET Lambda tools
      run: dotnet tool install --global Amazon.Lambda.Tools

    - name: Deploying Lambda
      working-directory: ./${{ env.AWS_LAMBDA_NAME }}
      run: dotnet lambda deploy-function ${{ env.AWS_LAMBDA_NAME }} --config-file aws-lambda-tools-production.json

    - name: Tagging Lambda with commit $GITHUB_SHA
      run: aws lambda tag-resource --resource arn:aws:lambda:${{ env.AWS_REGION }}:398018169858:function:${{ env.AWS_LAMBDA_NAME }} --tags GIT_COMMIT=$GITHUB_SHA
